require:
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.5

Metrics/AbcSize:
  Exclude:
    - lib/jekyll-diagrams/basic_*.rb

Metrics/BlockLength:
  Exclude:
    - jekyll-diagrams.gemspec
    - spec/**/*

Metrics/MethodLength:
  Max: 15

Naming/FileName:
  Exclude:
    - features/step_definitions/jekyll-diagrams.rb
    - spec/jekyll-diagrams_spec.rb
    - lib/jekyll-diagrams.rb

Naming/RescuedExceptionsVariableName:
  PreferredName: error

Style/ClassAndModuleChildren:
  Exclude:
    - features/support/env.rb
    - spec/spec_helper.rb

Style/Documentation:
  Enabled: false

RSpec/ExampleLength:
  Max: 10

RSpec/FilePath:
  Enabled: false

RSpec/MessageChain:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 2