AllCops:
  TargetRubyVersion: 2.5

Metrics/MethodLength:
  Max: 30

Naming/FileName:
  Exclude:
    - features/step_definitions/jekyll-diagrams.rb
    - lib/jekyll-diagrams.rb

Style/ClassAndModuleChildren:
  Exclude:
    - features/support/env.rb
    - spec/spec_helper.rb
    - test/test_helper.rb

Style/Documentation:
  Enabled: false
