# frozen_string_literal: true

source 'https://rubygems.org'

gem 'jekyll', '>= 3.8', '< 5.0'

gem 'bundler', '>= 1.15.0', '< 3.0'
gem 'coveralls', '>= 0.8', '< 1.0'
gem 'cucumber', '>= 3.0', '< 4.0'
gem 'minitest', '>= 5.10', '< 6.0'
gem 'pry', '>= 0.10', '< 1.0'
gem 'rake', '>= 12.0', '< 14.0'
gem 'rubocop', '>= 0.70', '< 1.0'
